version: 2

project_name: y509

builds:
  - binary: y509
    main: ./cmd/y509
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/kanywst/y509/internal/version.Version={{.Version}} -X github.com/kanywst/y509/internal/version.GitCommit={{.Commit}} -X github.com/kanywst/y509/internal/version.BuildDate={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - man/man1/*

# 自動的にシェル補完スクリプトを生成
release:
  prerelease: auto

checksum:
  name_template: "{{ .ProjectName }}-{{ .Version }}-checksums.txt"

homebrew_casks:
  - name: y509
    binaries:
      - y509
    manpages:
      - man/man1/y509.1
    generate_completions_from_executable:
      args:
        - completion
    homepage: "https://github.com/kanywst/y509"
    description: "Certificate Chain TUI Viewer"
    repository:
      owner: kanywst
      name: homebrew-y509
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

nfpms:
  - maintainer: kanywst
    description: Certificate Chain TUI Viewer
    homepage: https://github.com/kanywst/y509
    license: MIT
    formats:
      - deb
      - rpm
    contents:
      - src: completions/y509.bash
        dst: /usr/share/bash-completion/completions/y509
      - src: completions/y509.zsh
        dst: /usr/share/zsh/site-functions/_y509
      - src: man/man1/y509.1
        dst: /usr/share/man/man1/y509.1
