# This file was generated by GoReleaser. DO NOT EDIT.
cask "y509" do
  version "0.7.0"

  on_macos do
    on_intel do
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-darwin-amd64.tar.gz"
      sha256 "73ba125318b18c32973656b2b481bed68498361d7554e7bebe466bae1d1776db"
    end
    on_arm do
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-darwin-arm64.tar.gz"
      sha256 "91a78afeab4d7e533f2e940341dc9c74d5dafb5af39be63c165b41f26ba20cf5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-linux-amd64.tar.gz"
      sha256 "c93696514be05b9d6d169d45b8e34f0fc99aa58fdbdfc4b5a087aa1af20d0740"
    end
    on_arm do
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-linux-arm64.tar.gz"
      sha256 "6c4cf143ad3f4f15138d46c451b859beab8b2760fb51c9ada7b40d73bf549c7a"
    end
  end

  name "y509"
  desc "Certificate Chain TUI Viewer"
  homepage "https://github.com/kanywst/y509"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "y509"
  manpage "man/man1/y509.1"
  bash_completion "completions/y509.bash"
  zsh_completion "completions/y509.zsh"

  # No zap stanza required

end
