# This file was generated by GoReleaser. DO NOT EDIT.
cask "y509" do
  version "0.8.1"

  on_macos do
    on_intel do
      sha256 "8a3e17fedd2aab1bfd302515db6b7a7b5a9aa3bc7eec0402c22a8dd969cba261"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-darwin-amd64.tar.gz"
    end
    on_arm do
      sha256 "91709334c12356e56c0692d8e4245643b2860b5b1db88f40d357fe866a3491aa"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-darwin-arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e64efe7b2e32514e899b7bd8d84a3833a228dfb6bbd08f64581c277746baa827"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-linux-amd64.tar.gz"
    end
    on_arm do
      sha256 "67f8e0b7951962ffd72116d1e34ea08ffddd9f0bdb7cc69eb429228cc4484193"
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-linux-arm64.tar.gz"
    end
  end

  name "y509"
  desc "Certificate Chain TUI Viewer"
  homepage "https://github.com/kanywst/y509"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "y509"
  manpage "man/man1/y509.1"
  bash_completion "completions/y509.bash"
  zsh_completion "completions/y509.zsh"

  # No zap stanza required

end
