# This file was generated by GoReleaser. DO NOT EDIT.
cask "y509" do
  name "y509"
  desc "Certificate Chain TUI Viewer"
  homepage "https://github.com/kanywst/y509"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "y509"
  manpage "man/man1/y509.1"
  bash_completion "completions/y509.bash"
  zsh_completion "completions/y509.zsh"

  on_macos do
    on_intel do
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-darwin-amd64.tar.gz"
      sha256 "a53d924dc786b66f0f2f5a83489d19ed2cdc31fa2c0e14a52ef395ba43f46057"
    end
    on_arm do
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-darwin-arm64.tar.gz"
      sha256 "2ceff22b194ccecd11f4f5b83eccafcaecdb7451148950ad6c2452ed31445b13"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-linux-amd64.tar.gz"
      sha256 "e2e28b79d68312a58a37203773e275ab3ca4111b40a32a8b1c60934c7e961cf2"
    end
    on_arm do
      url "https://github.com/kanywst/y509/releases/download/v#{version}/y509-#{version}-linux-arm64.tar.gz"
      sha256 "3aa26613f018285ca0647ac4bee47d2661b67bd599a0676305ea8ec00a71d465"
    end
  end

  # No zap stanza required
end
