name: Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'demo.gif'
      - 'README.md'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Download dependencies
      run: go mod download

    - name: Lint
      run: make lint

    - name: Vulnerability check
      run: make vulncheck

    - name: Run tests
      run: make test-json > test-report.json

    - name: Annotate tests
      if: always()
      uses: guyarb/golang-test-annotations@v0.9.0
      with:
        test-results: test-report.json
